name: Build Tauri Network Analyzer

on: [push, pull_request]

jobs:
  build-macos-arm64:
    name: Build on macOS (ARM64)
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.15]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Add Rust target for aarch64-apple-darwin
      run: rustup target add aarch64-apple-darwin

    - name: Build Tauri app for macOS ARM64
      run: yarn tauri build --target aarch64-apple-darwin

    - name: Upload macOS ARM64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-arm64-app
        path: src-tauri/target/release

  build-macos-x64:
    name: Build on macOS (x64)
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18.15]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Build Tauri app for macOS ARM64
      run: yarn tauri build --target x86_64-apple-darwin

    - name: Upload macOS x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos-x64-app
        path: src-tauri/target/release

  build-windows:
    name: Build on Windows (x64)
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.15]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Build Tauri app for Windows x64
      run: yarn tauri build --target x86_64-pc-windows-msvc

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-app
        path: src-tauri/target/release
